src/AppBundle/Entity/Groupe.php
<?php

namespace AppBundle\Entity;

use Doctrine\Common\Collections\ArrayCollection;
use Doctrine\ORM\Mapping as ORM;
use Gedmo\Mapping\Annotation as Gedmo;
use Symfony\Component\Validator\Constraints as Assert;
use UserBundle\Entity\User;

/**
 * Groupe
 *
 * @ORM\Table(name="GRP_groupe")
 * @ORM\Entity(repositoryClass="AppBundle\Repository\GroupeRepository")
 * @Gedmo\Loggable(logEntryClass="AppBundle\Entity\Logs")
 */
class Groupe
{
    /**
     * @var int
     *
     * @ORM\Column(name="id", type="integer")
     * @ORM\Id
     * @ORM\GeneratedValue(strategy="AUTO")
     */
    private $id;

    /**
     * @var string
     *
     * @ORM\Column(name="nom", type="string", length=255)
     *
     * @Gedmo\Versioned()
     *
     * @Assert\NotBlank()
     */
    private $nom;

    /**
     * @var string
     *
     * @ORM\Column(name="description", type="string", length=255)
     *
     * @Gedmo\Versioned()
     *
     * @Assert\NotBlank()
     */
    private $description;

    /**
     * @var ArrayCollection|Individu[]
     *
     * @ORM\ManyToMany(targetEntity="AppBundle\Entity\Individu", cascade={"persist"}, inversedBy="groupes")
     * @ORM\JoinTable(name="GRP_groupe_individu")
     */
    private $individus;

    /**
     * @var ArrayCollection|Association[]
     *
     * @ORM\OneToMany(targetEntity="AppBundle\Entity\Association", mappedBy="groupe", orphanRemoval=true, cascade={"persist"})
     * @Assert\Valid(traverse=true)
     */
    private $associations;

    /**
     * @var ArrayCollection|Association[]
     *
     * @ORM\ManyToMany(targetEntity="AppBundle\Entity\Association", mappedBy="groupesAssocies")
     */
    private $associationsHeritees;

    /**
     * @var ArrayCollection|User[]
     *
     * @ORM\ManyToMany(targetEntity="UserBundle\Entity\User", mappedBy="groupesAcces", cascade={"persist"})
     */
    private $usersAutorises;

    /**
     * Constructor
     */
    public function __construct()
    {
        $this->individus = new ArrayCollection();
        $this->associations = new ArrayCollection();
        $this->associationsHeritees = new ArrayCollection();
    }

    /**
     * Get id
     *
     * @return int
     */
    public function getId()
    {
        return $this->id;
    }
    /**
    * Set id
    *
    * @param  id
    *
    * @return int
    */
    public function setId($id)
    {
        $this->id = $id;

        return $this->id;
    }
    /**
     * Set nom
     *
     * @param string $nom
     *
     * @return Groupe
     */
    public function setNom($nom)
    {
        $this->nom = $nom;

        return $this;
    }

    /**
     * Get nom
     *
     * @return string
     */
    public function getNom()
    {
        return $this->nom;
    }

    /**
     * Set description
     *
     * @param string $description
     *
     * @return Groupe
     */
    public function setDescription($description)
    {
        $this->description = $description;

        return $this;
    }

    /**
     * Get description
     *
     * @return string
     */
    public function getDescription()
    {
        return $this->description;
    }

    /**
     * Add individus
     *
     * @param Individu $individus
     *
     * @return Groupe
     */
    public function addIndividus(Individu $individus)
    {
        $this->individus[] = $individus;

        return $this;
    }

    /**
     * Remove individus
     *
     * @param Individu $individus
     */
    public function removeIndividus(Individu $individus)
    {
        $this->individus->removeElement($individus);
    }

    /**
     * Get individus
     *
     * @return ArrayCollection|Individu[]
     */
    public function getIndividus()
    {
        return $this->individus;
    }

    /**
     * Get AllIndividus
     *
     * Retourne les individus en "dur" du groupe et ceux qui sont issus d'une association avec d'autres groupes
     *
     * @return ArrayCollection|Individu[]
     */
    public function getAllIndividus()
    {
        // Récupération des individus "en dur" du groupe
        $individus = $this->individus->toArray();

        // Pour chaque groupe hérité, on récupère leurs individus
        foreach ($this->associations as $association) {
            $individus = array_unique(array_merge($individus, $association->getIndividusGroupesAssocies()->toArray()), SORT_REGULAR);
        }

        return new ArrayCollection($individus);
    }

    /**
     * Add association
     *
     * @param Association $association
     *
     * @return Groupe
     */
    public function addAssociation(Association $association)
    {
        $association->setGroupe($this);

        $this->associations[] = $association;

        return $this;
    }

    /**
     * Remove association
     *
     * @param Association $association
     *
     * @return Groupe
     */
    public function removeAssociation(Association $association)
    {
        $this->associations->removeElement($association);

        $association->setGroupe(null);

        return $this;
    }

    /**
     * Get associations
     *
     * @return ArrayCollection|Association[]
     */
    public function getAssociations()
    {
        return $this->associations;
    }

    /**
     * Get associationsHeritees
     *
     * @return ArrayCollection|Association[]
     */
    public function getAssociationsHeritees()
    {
        return $this->associationsHeritees;
    }

    /**
     * Get usersAutorises
     *
     * @return ArrayCollection|User[]
     */
    public function getUserAutorise()
    {
        return $this->usersAutorises;
    }

    /**
     * Add userAutorise
     *
     * @param User $user
     *
     * @return Groupe
     */
    public function addUserAutorise(User $user)
    {
        $this->usersAutorises[] = $user;

        $user->addGroupesAcce($this);

        return $this;
    }

    /**
     * Remove userAutorise
     *
     * @param User $user
     */
    public function removeUserAutorise(User $user)
    {
        $this->usersAutorises->removeElement($user);

        $user->removeGroupesAcce($this);
    }
}

src/AppBundle/Form/Type/GroupeType.php
<?php

namespace AppBundle\Form\Type;

use AppBundle\Entity\Individu;
use AppBundle\Form\Type\AssociationType;
use AppBundle\Repository\IndividuRepository;
use Doctrine\ORM\EntityRepository;
use Symfony\Bridge\Doctrine\Form\Type\EntityType;
use Symfony\Component\Form\AbstractType;
use Symfony\Component\Form\Extension\Core\Type\CollectionType;
use Symfony\Component\Form\FormBuilderInterface;
use Symfony\Component\OptionsResolver\OptionsResolver;

class GroupeType extends AbstractType
{
    /**
     * {@inheritdoc}
     */
    public function buildForm(FormBuilderInterface $builder, array $options)
    {
        $groupe = $builder->getData();
        $builder->add('nom')
                ->add('description')
                ->add('individus', EntityType::class, array(
                    'class'        => Individu::class,
                    'choice_label' => 'prenomNom',
                    'placeholder'  => '',
                    'multiple'     => true,
                    'required'     => false,
                    'query_builder' => function(IndividuRepository $er) {
                        $qb = $er->createQueryBuilder('i')->orderBy('i.prenom', 'ASC')->addOrderBy('i.nom', 'ASC');
                        return $qb;
                    }
                ))
                ->add('associations', CollectionType::class, array(
                    'entry_type'    => AssociationType::class,
                    'allow_add'     => true,
                    'allow_delete'  => true,
                    'by_reference'  => false,
                    'label'         => false,
                    'entry_options' => array(
                        'label' => false
                    ),
                    'required'      => false
                ));
    }

    /**
     * {@inheritdoc}
     */
    public function configureOptions(OptionsResolver $resolver)
    {
        $resolver->setDefaults(array(
                                   'data_class' => 'AppBundle\Entity\Groupe'
                               ));
    }

    /**
     * {@inheritdoc}
     */
    public function getBlockPrefix()
    {
        return 'appbundle_groupe';
    }
}

src/AppBundle/Controller/GroupeController.php
<?php

namespace AppBundle\Controller;

use AppBundle\Entity\Groupe;
use Sensio\Bundle\FrameworkExtraBundle\Configuration\Security;
use SosthenG\EntityPortationBundle\Export;
use Symfony\Bundle\FrameworkBundle\Controller\Controller;
use Sensio\Bundle\FrameworkExtraBundle\Configuration\Method;
use Sensio\Bundle\FrameworkExtraBundle\Configuration\Route;
use Symfony\Component\HttpFoundation\JsonResponse;
use Symfony\Component\HttpFoundation\Request;
use Symfony\Component\HttpFoundation\Response;

/**
 * Groupe controller.
 *
 * @Route("groupe")
 */
class GroupeController extends Controller
{
    /**
     * Lists all groupe entities.
     *
     * @Route("/", name="groupe_index")
     * @Method("GET")
     */
    public function indexAction()
    {
        $em = $this->getDoctrine()->getManager();

        $groupes = $em->getRepository('AppBundle:Groupe')->findAll(array(), array('nom' => 'ASC'));

        return $this->render('@App/groupe/tableau.html.twig', array(
            'groupes' => $groupes,
        ));
    }

    /**
     * Creates a new groupe entity.
     *
     * @Route("/new", name="groupe_new")
     * @Method({"GET", "POST"})
     * @Security("has_role('ROLE_ADMIN')")
     */
    public function newAction(Request $request)
    {
        $groupe = new Groupe();
        $form = $this->createForm('AppBundle\Form\Type\GroupeType', $groupe);
        $form->handleRequest($request);

        if ($form->isSubmitted() && $form->isValid()) {
            $em = $this->getDoctrine()->getManager();
            $groupe->addUserAutorise($this->getUser());
            $em->persist($groupe);
            $em->flush();

            return $this->redirectToRoute('groupe_index', array('id' => $groupe->getId()));
        }

        return $this->render('@App/groupe/new.html.twig', array(
            'groupe' => $groupe,
            'form' => $form->createView(),
        ));
    }

    /**
     * Finds and displays a groupe entity.
     *
     * @Route("/{id}", name="groupe_show", condition="request.isXmlHttpRequest()", requirements={"id": "\d+"})
     * @Method("GET")
     */
    public function showAction(Groupe $groupe)
    {
        $deleteForm = $this->createDeleteForm($groupe);

        return $this->render('@App/groupe/show.html.twig', array(
            'groupe' => $groupe,
            'delete_form' => $deleteForm->createView(),
            'confirm_message' => $this->getConfirmMessage($groupe->getNom())
        ));
    }

    /**
     * Displays a form to edit an existing groupe entity.
     *
     * @Route("/{id}/edit", name="groupe_edit", requirements={"id": "\d+"})
     * @Method({"GET", "POST"})
     * @Security("has_role('ROLE_ADMIN')")
     */
    public function editAction(Request $request, Groupe $groupe)
    {
        if (!$this->getUser()->hasAccess($groupe))
            throw $this->createAccessDeniedException("Vous n'êtes pas autorisé à modifier ce groupe");

        $deleteForm = $this->createDeleteForm($groupe);
        $editForm = $this->createForm('AppBundle\Form\Type\GroupeType', $groupe);
        $editForm->handleRequest($request);

        if ($editForm->isSubmitted() && $editForm->isValid()) {
            $this->getDoctrine()->getManager()->flush();

            return $this->redirectToRoute('groupe_index', array('id' => $groupe->getId()));
        }

        return $this->render('@App/groupe/edit.html.twig', array(
            'groupe' => $groupe,
            'form' => $editForm->createView(),
            'delete_form' => $deleteForm->createView(),
            'confirm_message' => $this->getConfirmMessage($groupe->getNom())
        ));
    }

    /**
     * Deletes a groupe entity.
     *
     * @Route("/{id}", name="groupe_delete", requirements={"id": "\d+"})
     * @Method("DELETE")
     * @Security("has_role('ROLE_ADMIN')")
     */
    public function deleteAction(Request $request, Groupe $groupe)
    {
        if (!$this->getUser()->hasAccess($groupe))
            throw $this->createAccessDeniedException("Vous n'êtes pas autorisé à supprimer ce groupe");

        $form = $this->createDeleteForm($groupe);
        $form->handleRequest($request);

        if ($form->isSubmitted() && $form->isValid()) {
            $em = $this->getDoctrine()->getManager();
            $em->remove($groupe);
            $em->flush();
        }

        return $this->redirectToRoute('groupe_index');
    }

    /**
     * @Route("{id}/export/{format}", name="groupe_export", requirements={"id": "\d+", "format" = "PDF|Excel2007|Excel5|CSV|HTML|OpenDocument"})
     * @Method("GET")
     */
    public function exportAction(Groupe $groupe, $format) {
        $individus = $groupe->getAllIndividus()->toArray();

        if ($format == 'PDF') {
            \PHPExcel_Settings::setPdfRenderer(\PHPExcel_Settings::PDF_RENDERER_MPDF, $this->get('kernel')->getRootDir()."/../vendor/mpdf/mpdf");
        }

        $exporter = new Export($this->get("phpexcel"), $this->get("translator"));

        $exporter->setEntities($individus, true);

        $nomExport = "Export du groupe ".$groupe->getNom();
        $exporter->setSheetTitle(substr($groupe->getNom(), 0, 31)); // Substr car sheetTitle doit <= 31 char
        $exporter->getProperties()->setTitle($nomExport);

        return $exporter->getResponse($format, $nomExport." ".date('Y-m-d'));
    }

    /**
     * Creates a form to delete a groupe entity.
     *
     * @param Groupe $groupe The groupe entity
     *
     * @return \Symfony\Component\Form\Form The form
     */
    private function createDeleteForm(Groupe $groupe)
    {
        return $this->createFormBuilder()
            ->setAction($this->generateUrl('groupe_delete', array('id' => $groupe->getId())))
            ->setMethod('DELETE')
            ->getForm()
        ;
    }

    /**
     * @param $nomGroupe
     *
     * @return string
     */
    private function getConfirmMessage($nomGroupe) {
        return "Voulez-vous vraiment supprimer le groupe ".$nomGroupe." ?";
    }
}

src/AppBundle/Resources/views/groupe/edit.html.twig
{% extends '@App/layout.html.twig' %}
{% set page_title = "Modification d'un groupe" %}
{%  block title %}{{ page_title }} {% endblock %}
{% block breadcrumb %}
    <li class="breadcrumb-item"><a href="{{ path("groupe_index") }}">Gestion des groupes</a></li>
    <li class="breadcrumb-item active">{{ page_title }}</li>
{% endblock %}

{% block content %}
    <div class="container-fluid">

        <div class="text-center">
            <a class="btn btn-default" href="{{ path('groupe_index') }}"><i class="fa fa-arrow-circle-left left"></i> Retour à la liste des groupes</a>
        </div>

        <div class="row mt-2">
            <div class="col-md-8 offset-md-2">
                <div class="row">
                    <div class="col-md-12 mb-1">

                        <div class="card">
                            <div class="card-block">
                                {{ include("@App/groupe/form.html.twig") }}

                                {{ form_start(delete_form, {'attr': {'class': 'd-inline float-md-right', 'onSubmit': 'return confirm("' ~ confirm_message ~ '")'}}) }}
                                <button type="submit" class="btn btn-danger align-content-center"><i class="fa fa-trash left"></i> Supprimer le groupe</button>
                                {{ form_rest(delete_form) }}
                                {{ form_end(delete_form) }}
                            </div>
                        </div>
                    </div>
                </div>
            </div>
        </div>
    </div>
{% endblock %}

{% block javascripts %}
    <script type="text/javascript">
        $(document).ready(function() {
            var $container = $('div#appbundle_groupe_associations');

            var index = $container.find(':input').length;

            $('#add_salle').click(function(e) {
                addAssociation($container);

                e.preventDefault();
                return false;
            });

            if (index != 0) {
                $container.children('div').each(function() {
                    addDeleteLink($(this));
                });
            }

            function addAssociation($container) {
                var template = $container.attr('data-prototype')
                        .replace(/__name__label__/g, 'Association n°' + (index+1))
                        .replace(/__name__/g,        index)
                    ;

                var $prototype = $(template);

                // Retire le groupe courant du menu déroulant
                $prototype.find('option[value="{{ groupe.id }}"]').remove();

                addDeleteLink($prototype);

                $container.find('.btn-floating').tooltip();

                $container.append($prototype);

                $prototype.find('.mdb-select').material_select();

                $prototype.find('.select-dropdown').each(function() {
                    var $ulSelect = $('#'+$(this).data('activates'));
                    if ($ulSelect.hasClass('multiple-select-dropdown') && $ulSelect.find('li.active').length == 0)
                        $(this).val('');
                });

                index++;
            }

            function addDeleteLink($prototype) {
                var $deleteLink = $('<a class="btn-floating btn-small red" data-toggle="tooltip" data-placement="left" title="Supprimer l\'association"><i class="fa fa-trash-o left"></i></a>');

                $prototype.append($deleteLink);
                $prototype.find($deleteLink).wrap('<div class="col-md-1"></div>');
                $prototype.addClass('row');
                $prototype.children('div').first().addClass('col-md-11');


                $deleteLink.click(function(e) {
                    $(this).tooltip('dispose');

                    $prototype.remove();

                    e.preventDefault();
                    return false;
                });
            }

            $('.btn-floating').tooltip();
        });
    </script>
{% endblock %}

src/AppBundle/Resources/views/groupe/form.html.twig
{{ form_start(form, {'attr': {'class': 'd-inline'}}) }}

{{ form_errors(form) }}

<div class="md-form">
    {{ form_widget(form.nom) }}
    {{ form_label(form.nom, "Nom") }}
    {{ form_errors(form.nom) }}
</div>

<div class="md-form">
    {{ form_widget(form.description) }}
    {{ form_label(form.description, "Description") }}
    {{ form_errors(form.description) }}
</div>

<div class="md-form">
    {{ form_widget(form.individus) }}
    {{ form_label(form.individus, "Individus") }}
    {{ form_errors(form.individus) }}
</div>

<h3>Associations</h3>

{{ form_row(form.associations) }}

<button type="submit" class="btn btn-primary">Enregistrer</button>
<button id="add_salle" class="btn btn-dark-green"><i class="fa fa-plus-circle left"></i> Ajouter une association</button>

{{ form_end(form) }}

src/AppBundle/Resources/views/groupe/new.html.twig
{% extends '@App/layout.html.twig' %}
{% set page_title = "Ajout d'un groupe" %}
{%  block title %}{{ page_title }} {% endblock %}
{% block breadcrumb %}
    <li class="breadcrumb-item"><a href="{{ path("groupe_index") }}">Gestion des groupes</a></li>
    <li class="breadcrumb-item active">{{ page_title }}</li>
{% endblock %}

{% block content %}
    <div class="container-fluid">

        <div class="text-center">
            <a class="btn btn-default" href="{{ path('groupe_index') }}"><i class="fa fa-arrow-circle-left left"></i> Retour à la liste des groupes</a>
        </div>

        <div class="row mt-2">
            <div class="col-md-8 offset-md-2">
                <div class="row">
                    <div class="col-md-12 mb-1">

                        <div class="card">
                            <div class="card-block">
                                {{ include("@App/groupe/form.html.twig") }}
                            </div>
                        </div>
                    </div>
                </div>
            </div>
        </div>
    </div>
{% endblock %}

{% block javascripts %}
    <script type="text/javascript">
        $(document).ready(function() {
            var $container = $('div#appbundle_groupe_associations');

            var index = $container.find(':input').length;

            $('#add_salle').click(function(e) {
                addAssociation($container);

                e.preventDefault();
                return false;
            });

            if (index != 0) {
                $container.children('div').each(function() {
                    addDeleteLink($(this));
                });
            }

            function addAssociation($container) {
                var template = $container.attr('data-prototype')
                    .replace(/__name__label__/g, 'Association n°' + (index+1))
                    .replace(/__name__/g,        index)
                ;

                var $prototype = $(template);

                addDeleteLink($prototype);

                $container.find('.btn-floating').tooltip();

                $container.append($prototype);

                $prototype.find('.mdb-select').material_select();

                $prototype.find('.select-dropdown').each(function() {
                    var $ulSelect = $('#'+$(this).data('activates'));
                    if ($ulSelect.hasClass('multiple-select-dropdown') && $ulSelect.find('li.active').length == 0)
                        $(this).val('');
                });

                index++;
            }

            function addDeleteLink($prototype) {
                var $deleteLink = $('<a class="btn-floating btn-small red" data-toggle="tooltip" data-placement="left" title="Supprimer l\'association"><i class="fa fa-trash-o left"></i></a>');

                $prototype.append($deleteLink);
                $prototype.find($deleteLink).wrap('<div class="col-md-1"></div>');
                $prototype.addClass('row');
                $prototype.children('div').first().addClass('col-md-11');


                $deleteLink.click(function(e) {
                    $(this).tooltip('dispose');

                    $prototype.remove();

                    e.preventDefault();
                    return false;
                });
            }

            $('.btn-floating').tooltip();
        });
    </script>
{% endblock %}

src/AppBundle/Resources/views/groupe/show.html.twig
<div class="modal-header">
    <p class="heading lead">{{ groupe.nom }}</p>
    <button type="button" class="close" data-dismiss="modal" aria-label="Fermer" title="Fermer">
        <span aria-hidden="true" class="white-text">&times;</span>
    </button>
</div>
<!--Body-->
<div class="modal-body">
    <div class="text-center">
        <i class="fa fa-info-circle fa-4x mb-1 animated rotateIn"></i>
    </div>
    <ul class="striped">
        <li><strong>Description :</strong> {{ groupe.description }}</li>
        <li>
            <div class="font-weight-bold text-center"><i class="fa fa-link"></i> Groupes liés :</div>
            {% if groupe.associations|length > 0 %}
                <div style="max-height: 200px; position:relative; overflow: auto;">
                    {% for association in groupe.associations %}
                    <ul class="listAssoc"><strong>{{ association.type }} :</strong>
                            {% for grp in association.groupesAssocies %}
                                <li>{{ grp.nom }}</li>
                            {% endfor %}
                        </ul>
                    {% endfor %}
                </div>
            {% endif %}
        </li>
        <li>
            <div class="row">
                <div class="font-weight-bold col-md-6"><i class="fa fa-group"></i> Individus ({{ groupe.allIndividus.count }}) :</div>

                {% if groupe.allIndividus.count > 0 %}
                    <div class="btn-group col-md-6">
                        <button class="btn btn-pink btn-sm dropdown-toggle" type="button" data-toggle="dropdown" aria-haspopup="true" aria-expanded="false"><i class="fa fa-download left"></i> Exporter</button>

                        <div class="dropdown-menu">
                            <a class="dropdown-item" href="{{ path("groupe_export", {id : groupe.id, format: "PDF"}) }}">PDF</a>
                            <a class="dropdown-item" href="{{ path("groupe_export", {id : groupe.id, format: "Excel5"}) }}">Excel (xls)</a>
                            <a class="dropdown-item" href="{{ path("groupe_export", {id : groupe.id, format: "Excel2007"}) }}">Excel (xlsx)</a>
                            <a class="dropdown-item" href="{{ path("groupe_export", {id : groupe.id, format: "CSV"}) }}">CSV</a>
                            <a class="dropdown-item" href="{{ path("groupe_export", {id : groupe.id, format: "OpenDocument"}) }}">OpenDocument</a>
                        </div>
                    </div>
                {% endif %}
            </div>
            {% if groupe.allIndividus.count > 0 %}
                <div style="max-height: 200px; position:relative; overflow: auto;">
                    {% for individu in groupe.allIndividus %}
                        <div>{{ individu.prenomNom }}</div>
                    {% endfor %}
                </div>
            {% endif %}
        </li>

    </ul>

</div>
<!--Footer-->
<div class="modal-footer">
    {% if is_granted("ROLE_ADMIN") and app.user.hasAccess(groupe) %}
        <a type="button" class="btn btn-orange" href="{{ path('groupe_edit', {'id': groupe.id}) }}"><i class="fa fa-pencil left"></i> Modifier</a>
        {{ form_start(delete_form, {'attr': {'class': 'd-inline', 'onSubmit': 'return confirm("' ~ confirm_message ~ '")'}}) }}
        <button type="submit" class="btn btn-danger align-content-center"><i class="fa fa-trash left"></i> Supprimer</button>
        {{ form_rest(delete_form) }}
        {{ form_end(delete_form) }}
    {% endif %}
</div>

src/AppBundle/Resources/views/groupe/tableau.html.twig
{% extends '@App/layout.html.twig' %}

{%  block title %}Gestion des groupes {% endblock %}
{% block breadcrumb %}
    <li class="breadcrumb-item">Gestion des groupes</li>
{% endblock %}
{% block content %}

<div class="container-fluid">
    <!-- First row -->
    <div class="row">
        <!-- First column -->
        <div class="col-md-12">
            <div class="row mb-1">
                <div class="col-md-5">
                    <div class="md-form">
                        <input placeholder="Rechercher" type="search" class="form-control" id="search" data-column="0,1,2,3">
                        <i class="clearInput fa fa-remove" data-input="search"></i>
                    </div>
                </div>
                <div class="col-md-7">
                    <div class="float-md-right">
                        {% if is_granted("ROLE_ADMIN") %}
                            <a class="btn btn-dark-green" href="{{ path("groupe_new") }}"><i class="fa fa-plus left"></i> Nouveau groupe</a>
                        {% endif %}
                    </div>
                </div>
            </div>
            <div class="row">
                <div class="col-md-12 mb-1" id="blocListIndividus">
                    <div class="card view hm-grey-light" style="position: relative">
                        <div class="table-responsive">
                            <table class="table tablesorter" id="listObjets">
                                <thead class="thead-inverse">
                                    <tr>
                                        <th>Nom</th>
                                        <th>Description</th>
                                        <th>Nombre d'associations</th>
                                        <th>Total d'individus</th>
                                        <th class="hidden-print">Actions</th>
                                    </tr>
                                </thead>
                                <tbody>
                                    {% for groupe in groupes %}
                                        <tr>
                                            <td>{{ groupe.nom }}</td>
                                            <td>{{ groupe.description }}</td>
                                            <td>{{ groupe.associations|length }}</td>
                                            <td>{{ groupe.allIndividus|length }}</td>
                                            <td>
                                                <a class="blue-text showBlockInfo" data-id="{{ groupe.id }}" data-toggle="tooltip" data-placement="top" title="Voir"><i class="fa fa-eye"></i></a>
                                                {% if is_granted("ROLE_ADMIN") and app.user.hasAccess(groupe) %}
                                                    <a class="orange-text" data-toggle="tooltip" data-placement="top" title="Modifier" href="{{ path('groupe_edit', {'id': groupe.id}) }}"><i class="fa fa-pencil"></i></a>
                                                    <div class="d-none">A</div> {# Sert uniquement pour le tri #}
                                                {% else %}
                                                    <div class="d-none">Z</div> {# Sert uniquement pour le tri #}
                                                {% endif %}
                                            </td>
                                        </tr>
                                    {% endfor %}
                                </tbody>
                            </table>
                        </div>

                    </div>
                </div>
                <div class="modal fade right" id="blocInfoGroupe" tabindex="-1" role="dialog" aria-labelledby="infoGroupe" aria-hidden="true">
                    <div class="modal-dialog modal-full-height modal-right modal-notify modal-info" role="document">
                        <div class="modal-content" id="contentInfoGroupe"></div>
                    </div>
                </div>
            </div>
            <!-- /.First column -->
        </div>
        <!-- /.First row -->
    </div>
{% endblock %}
{% block javascripts %}
    <script type="text/javascript">
        $(function() {
            $("#listObjets").tablesorter({
                theme: "bootstrap",
                widgets : [ "filter", "print" ],
                sortList: [[4,0], [0,0]],
                widgetOptions : {
                    filter_external : '#search',
                    filter_columnFilters: false,
                    print_title      : 'Liste des individus',
                    print_now        : true,
                    print_callback   : function(config, $table, printStyle){
                        $table.find(".hidden-print").remove(); // Supprime les colonnes à masquer
                        $.tablesorter.printTable.printOutput( config, $table.html(), printStyle );
                    }
                }
            });

            $('.clearInput').clearInput();
            $('#printTable').click(function(){
                $('#listObjets').trigger('printTable');
            });

            $('.showBlockInfo').click(function() {
                var url = "{{ path('groupe_show', {'id': '0'}) }}";
                url = url.replace("0", $(this).data('id'));
                $.get(url, function(data) {
                    $('#contentInfoGroupe').html(data);
                    $('#blocInfoGroupe').modal('show');
                });
            });
        });
    </script>
{% endblock %}