src/UserBundle/Entity/User.php
<?php

namespace UserBundle\Entity;

use AppBundle\Entity\Groupe;
use Doctrine\Common\Collections\ArrayCollection;
use Doctrine\ORM\Mapping as ORM;
use FOS\UserBundle\Model\User as BaseUser;
use Symfony\Bridge\Doctrine\Validator\Constraints\UniqueEntity;
use Symfony\Component\Validator\Constraints as Assert;
use SosthenG\EntityPortationBundle\Annotation\EntityPortation;
use SosthenG\EntityPortationBundle\Annotation\PortableMethod;

/**
 * @ORM\Table(name="GRP_user")
 * @ORM\Entity
 * @UniqueEntity(fields="username", message="Un utilisateur existe déjà avec cet identifiant.")
 * @UniqueEntity(fields="email", message="Un utilisateur existe déjà avec cette adresse email.")
 * @EntityPortation(csvDelimiter=";", sheetTitle="Export des utilisateurs", fallBackValue="N/A")
 */
class User extends BaseUser
{
    /**
     * @ORM\Column(name="id", type="integer")
     * @ORM\Id
     * @ORM\GeneratedValue(strategy="AUTO")
     */
    protected $id;

    /**
     * @Assert\NotBlank(message="fos_user.username.blank")
     * @Assert\Length(min=2, max=50, minMessage="fos_user.username.short", maxMessage="fos_user.username.long")
     */
    protected $username;

    /**
     * @Assert\NotBlank(message="fos_user.email.blank")
     * @Assert\Email(message="fos_user.email.invalid")
     * @Assert\Length(min=2, max=180, minMessage="fos_user.email.short", maxMessage="fos_user.email.long")
     */
    protected $email;

    /**
     * @Assert\NotBlank(message="fos_user.password.blank", groups={"Creation"})
     * @Assert\Length(min=2, max=4096, minMessage="fos_user.password.short")
     */
    protected $plainPassword;

    /**
     * @var ArrayCollection|Groupe[]
     *
     * @ORM\ManyToMany(targetEntity="AppBundle\Entity\Groupe", inversedBy="usersAutorises", cascade={"persist"})
     * @ORM\JoinTable(name="GRP_groupe_acces")
     * @ORM\JoinColumn(onDelete="CASCADE")
     */
    protected $groupesAcces;

    /**
     * Retourne le rôle maximum dans un format lisible
     *
     * @return string
     * @PortableMethod(label="Rôle", position="2")
     */
    public function getHigherRoleText() {
        if ($this->hasRole('ROLE_SUPER_ADMIN')) {
            return 'Super Administrateur';
        }
        elseif ($this->hasRole('ROLE_ADMIN')) {
            return 'Administrateur';
        }
        elseif ($this->hasRole('ROLE_USER')) {
            return 'Utilisateur';
        }

        return '';
    }

    /**
     * @inheritdoc
     * @PortableMethod(label="Identifiant", position="0")
     */
    public function getUsername()
    {
        return parent::getUsername();
    }

    /**
     * @inheritdoc
     * @PortableMethod(label="Adresse email", position="1")
     */
    public function getEmail()
    {
        return parent::getEmail();
    }

    /**
     * @inheritdoc
     */
    public function getRoles()
    {
        $roles = parent::getRoles();
        if (in_array('ROLE_SUPER_ADMIN', $roles)) {
            return array('ROLE_SUPER_ADMIN');
        }
        elseif (in_array('ROLE_ADMIN', $roles)) {
            return array('ROLE_ADMIN');
        }
        elseif (in_array('ROLE_USER', $roles)) {
            return array('ROLE_USER');
        }

        return $roles;
    }

    /**
     * Get groupes accessibles
     *
     * @return ArrayCollection|Groupe[]
     */
    public function getGroupesAcces()
    {
        return $this->groupesAcces;
    }

    /**
     * Add groupesAcce
     *
     * @param \AppBundle\Entity\Groupe $groupesAcce
     *
     * @return User
     */
    public function addGroupesAcce(\AppBundle\Entity\Groupe $groupesAcce)
    {
        $this->groupesAcces[] = $groupesAcce;

        return $this;
    }

    /**
     * Remove groupesAcce
     *
     * @param \AppBundle\Entity\Groupe $groupesAcce
     */
    public function removeGroupesAcce(\AppBundle\Entity\Groupe $groupesAcce)
    {
        $this->groupesAcces->removeElement($groupesAcce);
    }

    /**
     * @param Groupe $groupe
     *
     * @return bool
     */
    public function hasAccess(Groupe $groupe)
    {
        return $this->hasRole('ROLE_SUPER_ADMIN') || $this->groupesAcces->contains($groupe);
    }
}

src/UserBundle/Controller/UserController.php
<?php

namespace UserBundle\Controller;

use Sensio\Bundle\FrameworkExtraBundle\Configuration\Security;
use SosthenG\EntityPortationBundle\Export;
use Symfony\Component\HttpFoundation\Response;
use Symfony\Component\HttpKernel\Exception\AccessDeniedHttpException;
use Symfony\Component\Security\Core\Authentication\Token\UsernamePasswordToken;
use UserBundle\Entity\User;
use Symfony\Bundle\FrameworkBundle\Controller\Controller;
use Sensio\Bundle\FrameworkExtraBundle\Configuration\Method;
use Sensio\Bundle\FrameworkExtraBundle\Configuration\Route;
use Symfony\Component\HttpFoundation\Request;
use UserBundle\Form\Type\UserDeleteFormType;
use UserBundle\Form\Type\UserEditFormType;
use UserBundle\Form\Type\UserFormType;

/**
 * User controller.
 *
 * @Route("admin/user")
 * @Security("has_role('ROLE_SUPER_ADMIN')")
 */
class UserController extends Controller
{
    /**
     * Lists all user entities.
     *
     * @Route("/", name="admin_user_index")
     * @Method("GET")
     */
    public function indexAction()
    {
        $users = $this->get('fos_user.user_manager')->findUsers();

        return $this->render('@User/User/list.html.twig', array(
            'users' => $users,
        ));
    }

    /**
     * Creates a new user entity.
     *
     * @Route("/new", name="admin_user_new")
     * @Method({"GET", "POST"})
     */
    public function newAction(Request $request)
    {
        $userManager = $this->get('fos_user.user_manager');

        $user = $userManager->createUser();
        $user->setEnabled(true);

        $form = $this->createForm(UserFormType::class, $user);
        $form->handleRequest($request);

        if ($form->isSubmitted()) {
            if ($form->isValid()) {
                $userManager->updateUser($user);

                $this->addFlash('success', "L'utilisateur ".$user->getUsername()." a bien été ajouté.");

                return $this->redirectToRoute('admin_user_index');
            }
            else {
                $this->addFlash('error', "Merci de corriger les erreurs du formulaire avant de continuer.");
            }
        }

        return $this->render('@User/User/new.html.twig', array(
            'form' => $form->createView(),
        ));
    }

    /**
     * Displays a form to edit an existing user entity.
     *
     * @Route("/{id}/edit", name="admin_user_edit")
     * @Method({"GET", "POST"})
     */
    public function editAction(Request $request, User $user)
    {
        if ($user->hasRole('ROLE_ADMIN') && !$this->isGranted("ROLE_SUPER_ADMIN") && $user != $this->getUser()) {
            throw new AccessDeniedHttpException("Vous n'avez pas l'autorisation d'éditer cet utilisateur.");
        }

        $deleteForm = $this->createDeleteForm($user);
        $editForm = $this->createForm(UserEditFormType::class, $user);
        $editForm->handleRequest($request);

        if ($editForm->isSubmitted()) {
            if ($editForm->isValid()) {
                if ($user->getPlainPassword() == '') $user->setPlainPassword(null);
                $userManager = $this->get('fos_user.user_manager');

                $userManager->updateUser($user);

                $this->addFlash('success', "L'utilisateur " . $user->getUsername() . " a bien été modifié.");

                // Si l'utilisateur a modifié ses propres droits, on le déconnecte
                /** @var $currentUser User */
                $currentUser = $this->getUser();
                if ($user == $currentUser && $currentUser->getRoles() != $user->getRoles()) {
                    $this->get('security.token_storage')->setToken(null);
                    $this->get('session')->invalidate();
                    return $this->redirectToRoute('fos_user_security_logout');
                }

                return $this->redirectToRoute('admin_user_index');
            }
            else {
                $this->addFlash('error', "Merci de corriger les erreurs du formulaire avant de continuer.");
            }
        }

        return $this->render('@User/User/edit.html.twig', array(
            'user' => $user,
            'form' => $editForm->createView(),
            'confirm_message' => "Voulez-vous vraiment supprimer l'utilisateur ".$user->getUsername()." ?",
            'delete_form' => $deleteForm->createView(),
        ));
    }

    /**
     * Deletes a user entity.
     *
     * @Route("/{id}/delete", name="admin_user_delete")
     * @Method("DELETE")
     */
    public function deleteAction(Request $request, User $user)
    {
        if ($user->hasRole('ROLE_ADMIN') && !$this->isGranted("ROLE_SUPER_ADMIN") && $user != $this->getUser()) {
            throw new AccessDeniedHttpException("Vous n'avez pas l'autorisation de supprimer cet utilisateur.");
        }

        $form = $this->createDeleteForm($user);
        $form->handleRequest($request);

        if ($form->isSubmitted() && $form->isValid()) {
            $this->get('fos_user.user_manager')->deleteUser($user);
        }

        return $this->redirectToRoute('admin_user_index');
    }

    /**
     * Creates a simple form with an icon for deleting from a table
     *
     * @param User $user
     *
     * @return \Symfony\Component\HttpFoundation\Response
     */
    public function deleteFormAction(User $user) {
        $form = $this->createDeleteForm($user);

        return $this->render('@App/elements/delete_icon.html.twig',
                             array(
                                 'confirm_message' => "Voulez-vous vraiment supprimer l'utilisateur ".$user->getUsername()." ?",
                                 'delete_form' => $form->createView(),
                             )
        );
    }

    /**
     * @Route("/export/{format}", name="admin_user_export", requirements={"format" = "PDF|Excel2007|Excel5|CSV|HTML|XML|OpenDocument"})
     * @Method("GET")
     */
    public function exportAction($format) {
        $users = $this->get('fos_user.user_manager')->findUsers();

        if ($format == 'PDF') {
            \PHPExcel_Settings::setPdfRenderer(\PHPExcel_Settings::PDF_RENDERER_MPDF, $this->get('kernel')->getRootDir()."/../vendor/mpdf/mpdf");
        }

        $exporter = new Export($this->get("phpexcel"), $this->get("translator"));

        $exporter->setEntities($users, true);

        $nomExport = "Export users au ".date('Y-m-d');
        $exporter->setSheetTitle($nomExport);

        return $exporter->getResponse($format, $nomExport);
    }

    /**
     * Creates a form to delete a user entity.
     *
     * @param User $user The user entity
     *
     * @return \Symfony\Component\Form\Form The form
     */
    private function createDeleteForm(User $user)
    {
        return $this->createForm(UserDeleteFormType::class, null, array('action_url' => $this->generateUrl('admin_user_delete', array('id' => $user->getId()))));
    }
}

src/UserBundle/Resources/views/User/edit.html.twig
{% extends "@App/layout.html.twig" %}

{%  block title %}Modification d'un utilisateur{% endblock %}
{% block breadcrumb %}
    <li class="breadcrumb-item active">Administration</li>
    <li class="breadcrumb-item active"><a href="{{ path("admin_user_index") }}">Gestion des comptes</a></li>
    <li class="breadcrumb-item active">{{ user.username }}</li>
    <li class="breadcrumb-item">Modification</li>
{% endblock %}
{% block content %}
<div class="container-fluid">
    <!-- First row -->
    <div class="row">
        <!-- First column -->
        <div class="col-md-12">
            <div class="row">
                <div class="col-md-12 mb-1">
                    <div class="card">
                        <div class="card-block">
                            {{ include("@User/User/form.html.twig") }}
                            {{ form_start(delete_form, {'attr': {'class': 'd-inline float-md-right', 'onSubmit': 'return confirm("' ~ confirm_message ~ '")'}}) }}
                            <button type="submit" class="btn btn-danger align-content-center">Supprimer l'utilisateur</button>
                            {{ form_rest(delete_form) }}
                            {{ form_end(delete_form) }}
                        </div>
                    </div>
                </div>
            </div>
        </div>
    </div>

</div>
{% endblock %}

{% block javascripts %}
    <script type="text/javascript">
        $(function() {
           $('#user_edit_form_roles_0').change(function() {
               if ($(this).val() == 'ROLE_SUPER_ADMIN') {
                   $('#user_edit_form_groupesAcces').prop('disabled', true).parent('div').children('input.select-dropdown').prop('disabled', true);
               }
               else {
                   $('#user_edit_form_groupesAcces').prop('disabled', false).parent('div').children('input.select-dropdown').prop('disabled', false);
               }
           }).trigger('change');
        });
    </script>
{% endblock %}

src/UserBundle/Resources/views/User/form.html.twig
<div class="text-center mb-1">
    <a class="btn btn-blue-grey" href="{{ path("admin_user_index") }}"><i class="fa fa-arrow-circle-left left"></i> Retour à la gestion des utilisateurs</a>
</div>

{{ form_start(form, {'attr': {'class': 'd-inline'}}) }}

{{ form_errors(form) }}

<div class="md-form">
    <i class="fa fa-user prefix"></i>
    {{ form_widget(form.username, {'attr': {'class': 'form-control'}}) }}
    {{ form_label(form.username, "Identifiant") }}
    {{ form_errors(form.username) }} 
</div>

<div class="md-form">
    <i class="fa fa-envelope prefix"></i>
    {{ form_widget(form.email, {'attr': {'class': 'form-control'}}) }}
    {{ form_label(form.email, "Adresse email") }}
    {{ form_errors(form.email) }} 
</div>

{% if user is defined %}
    <p class="text-info"><i class="fa fa-info-circle"></i> Si vous ne voulez pas modifier le mot de passe, laissez ces champs vides.</p>
{% endif %}

<div class="md-form">
    <i class="fa fa-key prefix"></i>
    {{ form_widget(form.plainPassword.first, {'attr': {'class': 'form-control'}}) }}
    {{ form_label(form.plainPassword.first, "Mot de passe") }}
    {{ form_errors(form.plainPassword.first) }} 
</div>

<div class="md-form">
    <i class="fa fa-key prefix"></i>
    {{ form_widget(form.plainPassword.second, {'attr': {'class': 'form-control'}}) }}
    {{ form_label(form.plainPassword.second, "Confirmation du mot de passe") }}
    {{ form_errors(form.plainPassword.second) }} 
</div>

<div class="md-form">
    {{ form_widget(form.roles) }}
</div>

<div class="md-form">
    {{ form_widget(form.groupesAcces) }}
    {{ form_label(form.groupesAcces) }}
</div>

<button type="submit" class="btn btn-primary">Enregistrer l'utilisateur</button>

{{ form_end(form) }}

src/UserBundle/Resources/views/User/list.html.twig
{% extends "@App/layout.html.twig" %}
{%  block title %}Gestion des comptes {% endblock %}
{% block breadcrumb %}
    <li class="breadcrumb-item active">Administration</li>
    <li class="breadcrumb-item">Gestion des comptes</li>
{% endblock %}
{% block content %}

    <div class="container-fluid">
        <!-- First row -->
        <div class="row">
            <!-- First column -->
            <div class="col-md-12">
                <div class="row mb-1">
                    <div class="col-md-6">
                        <div class="md-form">
                            <input placeholder="Rechercher" type="search" class="form-control" id="searchUser" data-column="1,2,3">
                            <i class="clearInput fa fa-remove" data-input="searchUser"></i>
                        </div>
                    </div>
                    <div class="col-md-6">
                        <div class="float-md-right">
                            <a class="btn btn-dark-green" href="{{ path("admin_user_new") }}"><i class="fa fa-user-plus left"></i> Ajouter</a>

                            {{ include('@App/elements/export_button.html.twig', {'path': 'admin_user_export'}) }}
                        </div>
                    </div>
                </div>
                <div class="row">
                    <div class="col-md-12 mb-1">
                        <div class="card">
                            <div class="table-responsive">
                                <table class="table" id="listUsers">
                                    <thead class="thead-inverse">
                                        <tr>
                                            <th>Identifiant</th>
                                            <th>Email</th>
                                            <th>Rôle</th>
                                            <th class="hidden-print" data-sorter="false">Actions</th>
                                        </tr>
                                    </thead>
                                    <tbody>
                                        {% for user in users %}
                                            <tr>
                                                <td>{{ user.username }}</td>
                                                <td>{{ user.email }}</td>
                                                <td>{{ user.higherRoleText }}</td>
                                                <td class="hidden-print">
                                                    {% if 'ROLE_ADMIN' not in user.roles or user == app.user or is_granted("ROLE_SUPER_ADMIN") %}
                                                    <a class="orange-text" data-toggle="tooltip" data-placement="top" title="Modifier" href="{{ path('admin_user_edit', {'id': user.id}) }}"><i class="fa fa-pencil"></i></a>
                                                    {{ render(controller('UserBundle:User:deleteForm', { 'user' : user })) }}
                                                    {% endif %}
                                                </td>
                                            </tr>
                                        {% endfor %}
                                    </tbody>
                                </table>
                            </div>
                    </div>
                </div>
            </div>
            <!-- /.First column -->
        </div>
        <!-- /.First row -->
    </div>
{% endblock %}
{% block javascripts %}
    <script type="text/javascript">
        $(document).ready(function()
            {
                $("#listUsers").tablesorter({
                    theme: "bootstrap",
                    widgets : [ "filter", "print" ],
                    widgetOptions : {
                    filter_external : '#searchUser',
                    filter_columnFilters: false,
                    print_title      : 'Liste des utilisateurs',
                    print_now        : true,
                    print_callback   : function(config, $table, printStyle){
                        $table.find(".hidden-print").remove(); // Supprime les colonnes à masquer
                        $.tablesorter.printTable.printOutput( config, $table.html(), printStyle );
                    }
                    }
                });

                $('.clearInput').clearInput();
                $('#printUsersTable').click(function(){
                    $('#listUsers').trigger('printTable');
                });
            }
        );
    </script>
{% endblock %}

src/UserBundle/Resources/views/User/new.html.twig
{% extends "@App/layout.html.twig" %}
{%  block title %}Création d'un utilisateur{% endblock %}
{% block breadcrumb %}
    <li class="breadcrumb-item active">Administration</li>
    <li class="breadcrumb-item active"><a href="{{ path("admin_user_index") }}">Gestion des comptes</a></li>
    <li class="breadcrumb-item">Création d'un utilisateur</li>
{% endblock %}
{% block content %}
<div class="container-fluid">
    <!-- First row -->
    <div class="row">
        <!-- First column -->
        <div class="col-md-12">
            <div class="row">
                <div class="col-md-12 mb-1">
                    <div class="card">
                        <div class="card-block">
                            {{ include("@User/User/form.html.twig") }}
                        </div>
                    </div>
                </div>
            </div>
        </div>
    </div>

</div>
{% endblock %}

{% block javascripts %}
    <script type="text/javascript">
        $(function() {
            $('#user_edit_form_roles_0').change(function() {
                if ($(this).val() == 'ROLE_SUPER_ADMIN') {
                    $('#user_edit_form_groupesAcces').prop('disabled', true).parent('div').children('input.select-dropdown').prop('disabled', true);
                }
                else {
                    $('#user_edit_form_groupesAcces').prop('disabled', false).parent('div').children('input.select-dropdown').prop('disabled', false);
                }
            });
        });
    </script>
{% endblock %}