src/AppBundle/Entity/Logs.php
<?php

namespace AppBundle\Entity;

use Gedmo\Loggable\Entity\MappedSuperclass\AbstractLogEntry;
use Doctrine\ORM\Mapping as ORM;
use SosthenG\EntityPortationBundle\Annotation\EntityPortation;
use SosthenG\EntityPortationBundle\Annotation\PortableMethod;
use SosthenG\EntityPortationBundle\Annotation\PortableProperty;

/**
 * @ORM\Table(name="GRP_logs")
 * @ORM\Entity(repositoryClass="Gedmo\Loggable\Entity\Repository\LogEntryRepository")
 * @EntityPortation(csvDelimiter=";", fallBackValue="N/A", sheetTitle="Logs")
 */
class Logs extends AbstractLogEntry
{
    /**
     * @PortableMethod(label="Date / Heure", methodType="GETTER", property="loggedAt", position="0")
     */
    public function getLoggedAt()
    {
        return parent::getLoggedAt();
    }

    /**
     * @PortableMethod(label="Utilisateur", methodType="GETTER", property="username", position="1")
     */
    public function getUsername()
    {
        return parent::getUsername();
    }

    /**
     * @return string
     * @PortableMethod(label="Action", methodType="GETTER", property="action", position="2")
     */
    public function getActionLabel()
    {
        switch ($this->action) {
            case 'create':
                return 'Création';
                break;
            case 'update':
                $label = 'Modification : ';
                foreach ($this->getData() as $editedVal => $values) {
                    $label .= $editedVal . ', ';
                }
                return trim($label, ', ');
                break;
            case 'remove':
                return 'Suppression';
                break;
            default:
                return $this->action;
                break;
        }
    }

    /**
     * @return string
     * @PortableMethod(label="Objet", methodType="GETTER", property="objectClass", position="3")
     */
    public function getObjectClassName()
    {
        return explode('\\', $this->objectClass)[2];
    }

    /**
     * @return string
     * @PortableMethod(label="Identifiant / Nom", methodType="GETTER", property="objectId", position="4")
     */
    public function getObjectName()
    {
        if ($this->getObjectClassName() == 'Groupe')
            return !empty($this->data['nom']) ? $this->objectId.' / '.$this->data['nom'] : $this->objectId;
        else
            return !empty($this->data['nom']) && !empty($this->data['prenom']) ? $this->objectId.' / '.$this->data['prenom'].' '.$this->data['nom'] : $this->objectId;
    }
}

src/AppBundle/Controller/WatchdogController.php
<?php

namespace AppBundle\Controller;

use Doctrine\DBAL\Connection;
use Sensio\Bundle\FrameworkExtraBundle\Configuration\Method;
use Sensio\Bundle\FrameworkExtraBundle\Configuration\Security;
use SosthenG\EntityPortationBundle\Export;
use Symfony\Bundle\FrameworkBundle\Controller\Controller;
use Sensio\Bundle\FrameworkExtraBundle\Configuration\Route;
use Symfony\Component\HttpFoundation\Request;
use Symfony\Component\HttpFoundation\Response;

/**
 * WatchdogController controller.
 *
 * @Route("admin/watchdog")
 * @Security("has_role('ROLE_SUPER_ADMIN')")
 */
class WatchdogController extends Controller
{
    /**
     * @Route("/", name="admin_watch_index")
     */
    public function watchAction()
    {
        $em = $this->getDoctrine()->getManager();

        $logs = $em->getRepository('AppBundle:Logs')->findBy(array(), array('loggedAt' => 'DESC'));

        // TODO : Améliorer avec pagination etc.

        return $this->render('@App/watchdog/index.html.twig', array(
            'logs' => $logs,
            'clear_form' => $this->createClearForm()->createView(),
            'confirm_message' => 'Voulez-vous vraiment vider les logs ?'));
    }

    /**
     * @Route("/export/{format}", name="logs_export", requirements={"format" = "PDF|Excel2007|Excel5|CSV|HTML|OpenDocument"})
     * @Method("GET")
     */
    public function exportAction($format) {
        $logs = $this->getDoctrine()->getManager()->getRepository("AppBundle:Logs")->findAll();

        if ($format == 'PDF') {
            \PHPExcel_Settings::setPdfRenderer(\PHPExcel_Settings::PDF_RENDERER_MPDF, $this->get('kernel')->getRootDir()."/../vendor/mpdf/mpdf");
        }

        $exporter = new Export($this->get("phpexcel"), $this->get("translator"));

        $exporter->setEntities($logs, true);

        $nomExport = "Logs au ".date('Y-m-d');
        $exporter->setSheetTitle($nomExport);

        return $exporter->getResponse($format, $nomExport);
    }

    /**
     * Creates a form to delete the logs
     *
     * @return \Symfony\Component\Form\Form The form
     */
    private function createClearForm()
    {
        return $this->createFormBuilder()
                    ->setAction($this->generateUrl('logs_clear'))
                    ->setMethod('DELETE')
                    ->getForm()
            ;
    }

    /**
     * @Route("/clear", name="logs_clear")
     * @Method("DELETE")
     */
    public function clearAction(Request $request)
    {
        $form = $this->createClearForm();
        $form->handleRequest($request);

        if ($form->isSubmitted() && $form->isValid()) {
            /** @var Connection $connection */
            $connection = $this->getDoctrine()->getConnection();
            $platform   = $connection->getDatabasePlatform();
            $connection->executeUpdate($platform->getTruncateTableSQL('GRP_logs'));
            $this->addFlash('success', 'Les logs ont été vidés');
        }
        else {
            $this->addFlash('error', 'Impossible de vider les logs.');
        }
        return $this->redirectToRoute('admin_watch_index');
    }
}

src/AppBundle/Resources/views/watchdog/index.html.twig
{% extends '@App/layout.html.twig' %}

{%  block title %}Centre de surveillance {% endblock %}
{% block breadcrumb %}
    <li class="breadcrumb-item">Centre de surveillance</li>
{% endblock %}
{% block content %}

<div class="container-fluid">
    <!-- First row -->
    <div class="row">
        <!-- First column -->
        <div class="col-md-12">
            <div class="row mb-1">
                <div class="col-md-5">
                    <div class="md-form">
                        <input placeholder="Rechercher" type="search" class="form-control" id="search" data-column="0,1,2,3,4">
                        <i class="clearInput fa fa-remove" data-input="search"></i>
                    </div>
                </div>
                {% if logs|length > 0 %}
                <div class="col-md-7">
                    <div class="float-md-right">
                        {{ form_start(clear_form, {'attr': {'class': 'd-inline', 'onSubmit': 'return confirm("' ~ confirm_message ~ '")'}}) }}
                        <button type="submit" class="btn btn-danger"><i class="fa fa-trash left"></i> Vider les logs</button>
                        {{ form_rest(clear_form) }}
                        {{ form_end(clear_form) }}

                        {{ include('@App/elements/export_button.html.twig', {'path': 'logs_export'}) }}
                    </div>
                </div>
                {% endif %}
            </div>
            <div class="row">
                <div class="col-md-12 mb-1" id="blocListLogs">
                    <div class="card view hm-grey-light" style="position: relative">
                        <div class="table-responsive">
                            <table class="table tablesorter" id="listObjets">
                                <thead class="thead-inverse">
                                    <tr>
                                        <th>Date / Heure</th>
                                        <th>Utilisateur</th>
                                        <th>Action</th>
                                        <th>Objet</th>
                                        <th>Identifiant / Nom</th>
                                    </tr>
                                </thead>
                                <tbody>
                                    {% for log in logs %}
                                        <tr>
                                            <td>{{ log.loggedAt|date('Y-m-d H:i:s') }}</td>
                                            <td>{{ log.username }}</td>
                                            <td>{{ log.actionLabel }}</td>
                                            <td>{{ log.objectClassName }}</td>
                                            <td>{{ log.objectName }}</td>
                                        </tr>
                                    {% endfor %}
                                </tbody>
                            </table>
                        </div>

                    </div>
                </div>
            </div>
        <!-- /.First column -->
        </div>
    <!-- /.First row -->
    </div>
{% endblock %}
{% block javascripts %}
    <script type="text/javascript">
        $(function() {
            $("#listObjets").tablesorter({
                theme: "bootstrap",
                widgets : [ "filter", "print" ],
                sortList: [[0,1]],
                widgetOptions : {
                    filter_external : '#search',
                    filter_columnFilters: false,
                    print_title      : 'Logs',
                    print_now        : true,
                    print_callback   : function(config, $table, printStyle){
                        $table.find(".hidden-print").remove(); // Supprime les colonnes à masquer
                        $.tablesorter.printTable.printOutput( config, $table.html(), printStyle );
                    }
                }
            });

            $('.clearInput').clearInput();
            $('#printTable').click(function(){
                $('#listObjets').trigger('printTable');
            });
        });
    </script>
{% endblock %}