src/AppBundle/Entity/Individu.php
<?php

namespace AppBundle\Entity;

use Doctrine\Common\Collections\ArrayCollection;
use Doctrine\ORM\Mapping as ORM;
use Gedmo\Mapping\Annotation as Gedmo;
use SosthenG\EntityPortationBundle\Annotation\EntityPortation;
use SosthenG\EntityPortationBundle\Annotation\PortableMethod;
use SosthenG\EntityPortationBundle\Annotation\PortableProperty;
use Symfony\Bridge\Doctrine\Validator\Constraints\UniqueEntity;
use Doctrine\ORM\Mapping\UniqueConstraint;
use Symfony\Component\Validator\Constraints as Assert;

/**
 * Individu
 *
 * @ORM\Table(name="GRP_individu", uniqueConstraints={@UniqueConstraint(name="util_unique", columns={"identifiant", "statut_id"})})
 * @ORM\Entity(repositoryClass="AppBundle\Repository\IndividuRepository")
 * @Gedmo\Loggable(logEntryClass="AppBundle\Entity\Logs")
 * @UniqueEntity(fields={"identifiant", "statut"}, message="Un utilisateur existe déjà avec cet identifiant.")
 * @EntityPortation(csvDelimiter=";", fallBackValue="N/A", sheetTitle="Export des individus")
 */
class Individu
{
    /**
     * @var int
     *
     * @ORM\Column(name="id", type="integer")
     * @ORM\Id
     * @ORM\GeneratedValue(strategy="AUTO")
     */
    private $id;

    /**
     * @var string
     *
     * @ORM\Column(name="identifiant", type="string", length=50)
     * @Assert\NotBlank()
     *
     * @Gedmo\Versioned()
     *
     * @PortableProperty(label="Identifiant", position="0")
     */
    private $identifiant;

    /**
     * @var Statut
     *
     * @ORM\ManyToOne(targetEntity="AppBundle\Entity\Statut")
     * @ORM\JoinColumn(nullable=false)
     * @Assert\NotNull()
     *
     * @Gedmo\Versioned()
     */
    private $statut;

    /**
     * @var string
     *
     * @ORM\Column(name="nom", type="string", length=255)
     * @Assert\NotBlank()
     *
     * @Gedmo\Versioned()
     *
     * @PortableProperty(label="Nom", position="3")
     */
    private $nom;

    /**
     * @var string
     *
     * @ORM\Column(name="prenom", type="string", length=255)
     * @Assert\NotBlank()
     *
     * @Gedmo\Versioned()
     *
     * @PortableProperty(label="Prénom", position="2")
     */
    private $prenom;

    /**
     * @var string
     *
     * @ORM\Column(name="email", type="string", length=255)
     * @Assert\NotBlank()
     * @Assert\Email()
     *
     * @Gedmo\Versioned()
     *
     * @PortableProperty(label="Email", position="4")
     */
    private $email;

    /**
     * @var string
     *
     * @ORM\Column(name="telephone", type="string", length=255)
     * @Assert\NotBlank()
     *
     * @Gedmo\Versioned()
     *
     * @PortableProperty(label="Téléphone", position="5")
     */
    private $telephone;

    /**
     * @var \DateTime
     *
     * @ORM\Column(name="date_naissance", type="date", nullable=false)
     * @Assert\NotBlank()
     * @Assert\Date()
     *
     * @Gedmo\Versioned()
     *
     * @PortableProperty(label="Date de naissance", position="6", getter="getDateNaissanceFormatted")
     */
    private $dateNaissance;

    /**
     * @var Groupe[]
     *
     * @ORM\ManyToMany(targetEntity="AppBundle\Entity\Groupe", mappedBy="individus", cascade={"persist"})
     */
    private $groupes;

    /**
     * Constructor
     */
    public function __construct()
    {
        $this->groupes = new ArrayCollection();
    }

    /**
     * Get id
     *
     * @return int
     */
    public function getId()
    {
        return $this->id;
    }

    /**
     * Set identifiant
     *
     * @param string $identifiant
     *
     * @return Individu
     */
    public function setIdentifiant($identifiant)
    {
        $this->identifiant = $identifiant;

        return $this;
    }

    /**
     * Get identifiant
     *
     * @return string
     */
    public function getIdentifiant()
    {
        return $this->identifiant;
    }

    /**
     * Set statut
     *
     * @param Statut $statut
     *
     * @return Individu
     */
    public function setStatut($statut)
    {
        $this->statut = $statut;

        return $this;
    }

    /**
     * Get statut
     *
     * @return Statut
     */
    public function getStatut()
    {
        return $this->statut;
    }

    /**
     * Get statut libelle
     *
     * @return string
     *
     * @PortableMethod(label="Statut", position="1")
     */
    public function getStatutLibelle()
    {
        return (!empty($this->statut)) ? $this->statut->getLibelle() : 'N/A';
    }

    /**
     * Set nom
     *
     * @param string $nom
     *
     * @return Individu
     */
    public function setNom($nom)
    {
        $this->nom = $nom;

        return $this;
    }

    /**
     * Get nom
     *
     * @return string
     */
    public function getNom()
    {
        return $this->nom;
    }

    /**
     * Set prenom
     *
     * @param string $prenom
     *
     * @return Individu
     */
    public function setPrenom($prenom)
    {
        $this->prenom = $prenom;

        return $this;
    }

    /**
     * Get prenom
     *
     * @return string
     */
    public function getPrenom()
    {
        return $this->prenom;
    }

    /**
     * Get prenomNom
     *
     * @return string
     */
    public function getPrenomNom()
    {
        return $this->prenom . ' ' . $this->nom;
    }

    /**
     * Set email
     *
     * @param string $email
     *
     * @return Individu
     */
    public function setEmail($email)
    {
        $this->email = $email;

        return $this;
    }

    /**
     * Get email
     *
     * @return string
     */
    public function getEmail()
    {
        return $this->email;
    }

    /**
     * Set telephone
     *
     * @param string $telephone
     *
     * @return Individu
     */
    public function setTelephone($telephone)
    {
        $this->telephone = $telephone;

        return $this;
    }

    /**
     * Get telephone
     *
     * @return string
     */
    public function getTelephone()
    {
        return $this->telephone;
    }

    /**
     * Set dateNaissance
     *
     * @param \DateTime $dateNaissance
     *
     * @return Individu
     */
    public function setDateNaissance($dateNaissance)
    {
        $this->dateNaissance = $dateNaissance;

        return $this;
    }

    /**
     * Get dateNaissance
     *
     * @return \DateTime
     */
    public function getDateNaissance()
    {
        return $this->dateNaissance;
    }

    /**
     * Get dateNaissanceFormatted
     *
     * @return string
     */
    public function getDateNaissanceFormatted($format = 'Y-m-d')
    {
        return $this->dateNaissance->format($format);
    }

    /**
     * Add groupe
     *
     * @param Groupe $groupe
     *
     * @return Individu
     */
    public function addGroupe(Groupe $groupe)
    {
        $this->groupes[] = $groupe;

        $groupe->addIndividus($this);

        return $this;
    }

    /**
     * Remove groupe
     *
     * @param Groupe $groupe
     *
     * @return Individu
     */
    public function removeGroupe(Groupe $groupe)
    {
        $this->groupes->removeElement($groupe);

        $groupe->removeIndividus($this);

        return $this;
    }

    /**
     * Get groupes
     *
     * @return ArrayCollection|Groupe[]
     */
    public function getGroupes()
    {
        return $this->groupes;
    }

    /**
     * Récupère tous les groupes dans lesquels est l'utilisateur, y compris indirectement
     *
     * @return ArrayCollection|Groupe[]
     */
    public function getAllGroupes() {
        $groupes = $this->groupes;

        foreach ($this->groupes as $groupe) {
            foreach ($groupe->getAssociationsHeritees() as $association) {
                if (!$groupes->contains($association->getGroupe())) {
                    if ($association->getType() == 'UNION') {
                        $groupes->add($association->getGroupe());
                    }
                    elseif ($association->getType() == 'INTERSECTION') {
                        if ($association->getIndividusGroupesAssocies()->contains($this)) {
                            $groupes->add($association->getGroupe());
                        }
                    }
                }
            }
        }

        return $groupes;
    }
}

src/AppBundle/Form/Type/IndividuType.php
<?php

namespace AppBundle\Form\Type;

use AppBundle\Repository\GroupeRepository;
use Doctrine\ORM\EntityRepository;
use Symfony\Bridge\Doctrine\Form\Type\EntityType;
use Symfony\Component\Form\AbstractType;
use Symfony\Component\Form\Extension\Core\Type\BirthdayType;
use Symfony\Component\Form\Extension\Core\Type\EmailType;
use Symfony\Component\Form\FormBuilderInterface;
use Symfony\Component\OptionsResolver\OptionsResolver;
use UserBundle\Entity\User;

class IndividuType extends AbstractType
{
    /**
     * {@inheritdoc}
     */
    public function buildForm(FormBuilderInterface $builder, array $options)
    {
        $builder->add('identifiant')
            ->add('nom')
            ->add('prenom')
            ->add('email', EmailType::class)
            ->add('telephone')
            ->add('dateNaissance', BirthdayType::class, array(
                'widget' => 'single_text',
                'html5' => false,
                'format' => 'yyyy-MM-dd'))
            ->add('statut', EntityType::class, array(
                'class' => 'AppBundle\Entity\Statut',
                'choice_label' => 'libelle',
                'multiple' => false,
            ))
            ->add('groupes', EntityType::class, array(
                'class' => 'AppBundle\Entity\Groupe',
                'choice_label' => 'nom',
                'multiple' => true,
                'required' => false,
                'by_reference' => false // Force l'utilisation du setter pour modifier cet attribut (le setter a été modifié pour que les groupes soient bien persistés)
            ))
        ;
    }
    
    /**
     * {@inheritdoc}
     */
    public function configureOptions(OptionsResolver $resolver)
    {
        $resolver->setDefaults(array(
            'data_class' => 'AppBundle\Entity\Individu'
        ));
    }

    /**
     * {@inheritdoc}
     */
    public function getBlockPrefix()
    {
        return 'appbundle_individu';
    }


}

src/AppBundle/Resources/views/individu/checkbox.html.twig
<input type="checkbox" class="lineCheckbox" id="checkbox_{{ individu.id }}" data-id="{{ individu.id }}">
<label for="checkbox_{{ individu.id }}"></label>

src/AppBundle/Resources/views/individu/edit.html.twig
{% extends '@App/layout.html.twig' %}

{%  block title %}Modification de {{ individu.prenomNom }} {% endblock %}
{% block breadcrumb %}
    <li class="breadcrumb-item active"><a href="{{ path("individu_index") }}">Gestion des individus</a></li>
    <li class="breadcrumb-item">Modification de {{ individu.prenomNom }}</li>
{% endblock %}
{% block content %}
    <div class="container-fluid">
        <!-- First row -->
        <div class="row">
            <!-- First column -->
            <div class="col-md-12">
                <div class="row">
                    <div class="col-md-12 mb-1">
                        <div class="card">
                            <div class="card-block">
                                {{ include("@App/individu/form.html.twig") }}
                                {{ form_start(delete_form, {'attr': {'class': 'd-inline float-md-right', 'onSubmit': 'return confirm("' ~ confirm_message ~ '")'}}) }}
                                <button type="submit" class="btn btn-danger align-content-center">Supprimer l'individu</button>
                                {{ form_rest(delete_form) }}
                                {{ form_end(delete_form) }}
                            </div>
                        </div>
                    </div>
                </div>
            </div>
        </div>

    </div>
{% endblock %}

src/AppBundle/Resources/views/individu/form.html.twig
<div class="text-center mb-1">
    <a class="btn btn-blue-grey" href="{{ path("individu_index") }}"><i class="fa fa-arrow-circle-left left"></i> Retour à la gestion des individus</a>
</div>

{{ form_start(form, {'attr': {'class': 'd-inline'}}) }}

{{ form_errors(form) }}

<div class="md-form">
    <i class="fa fa-user prefix"></i>
    {{ form_widget(form.identifiant, {'attr': {'class': 'form-control'}}) }}
    {{ form_label(form.identifiant, "Identifiant") }}
    {{ form_errors(form.identifiant) }}
</div>

<div class="md-form">
    {{ form_widget(form.statut, {'attr': {'class': 'mdb-select'}}) }}
    {{ form_label(form.statut, "Statut") }}
    {{ form_errors(form.statut) }}
</div>

<div class="md-form">
    <i class="fa fa-info-circle prefix"></i>
    {{ form_widget(form.nom, {'attr': {'class': 'form-control'}}) }}
    {{ form_label(form.nom, "Nom") }}
    {{ form_errors(form.nom) }}
</div>

<div class="md-form">
    <i class="fa fa-info-circle prefix"></i>
    {{ form_widget(form.prenom, {'attr': {'class': 'form-control'}}) }}
    {{ form_label(form.prenom, "Prénom") }}
    {{ form_errors(form.prenom) }}
</div>

<div class="md-form">
    <i class="fa fa-envelope prefix"></i>
    {{ form_widget(form.email, {'attr': {'class': 'form-control'}}) }}
    {{ form_label(form.email, "Adresse email") }}
    {{ form_errors(form.email) }} 
</div>

<div class="md-form">
    <i class="fa fa-phone prefix"></i>
    {{ form_widget(form.telephone, {'attr': {'class': 'form-control'}}) }}
    {{ form_label(form.telephone, "Téléphone") }}
    {{ form_errors(form.telephone) }}
</div>

<div class="md-form">
    <i class="fa fa-calendar prefix"></i>
    {{ form_widget(form.dateNaissance, {'attr': {'class': 'form-control datepicker', 'placeholder': 'Sélectionner une date'}}) }}
    {{ form_label(form.dateNaissance, "Date de naissance") }}
    {{ form_errors(form.dateNaissance) }}
</div>

<div class="md-form">
    {{ form_widget(form.groupes, {'attr': {'class': 'mdb-select'}}) }}
    {{ form_label(form.groupes, "Groupes") }}
    {{ form_errors(form.groupes) }}
</div>

<button type="submit" class="btn btn-primary">Enregistrer l'individu</button>

{{ form_end(form) }}

src/AppBundle/Resources/views/individu/index.html.twig
{% extends '@App/layout.html.twig' %}

{%  block title %}Gestion des individus {% endblock %}
{% block breadcrumb %}
    <li class="breadcrumb-item">Gestion des individus</li>
{% endblock %}
{% block content %}

<div class="container-fluid">
    <!-- First row -->
    <div class="row">
        <!-- First column -->
        <div class="col-md-12">
            <div class="row mb-1">
                <div class="col-md-5">
                    <div class="md-form">
                        <input placeholder="Rechercher" type="search" class="form-control" id="search" data-column="1,2,3,4,5">
                        <i class="clearInput fa fa-remove" data-input="search"></i>
                    </div>
                </div>
                <div class="col-md-7">
                    <div class="float-md-right">
                        {% if is_granted("ROLE_ADMIN") %}
                            <a class="btn btn-dark-green" href="{{ path("individu_new") }}"><i class="fa fa-user-plus left"></i> Ajouter</a>
                            <a class="btn btn-purple" href="{{ path("individu_import") }}"><i class="fa fa-file-excel-o left"></i> Importer</a>
                        {% endif %}
                        {% if individus.count > 0 %}
                            {{ include('@App/elements/export_button.html.twig', {'path': 'individu_export'}) }}
                        {% endif %}
                    </div>
                </div>
            </div>
            <div class="row">
                <div class="col-md-12 mb-1" id="blocListIndividus">
                    <div class="card view hm-grey-light" style="position: relative">
                        <div class="table-responsive">
                            <table class="table tablesorter" id="listObjets">
                                <thead class="thead-inverse">
                                    <tr>
                                        <th class="hidden-print" data-sorter="false" data-checked="false" id="checkAll"><i class="fa fa-square-o"></i></th>
                                        <th>Identifiant</th>
                                        <th>Statut</th>
                                        <th>Nom</th>
                                        <th>Prénom</th>
                                        <th>Email</th>
                                        <th class="hidden-print" data-sorter="false">Actions</th>
                                    </tr>
                                </thead>
                                <tbody>
                                    {% for individu in individus %}
                                        {{ include('@App/individu/row.html.twig', {'individu': individu}) }}
                                    {% endfor %}
                                </tbody>
                            </table>
                        </div>
                        <nav class="pager-container flex-center" style="z-index: 0;">
                            <ul class="pagination pg-dark">
                                <li class="page-item pager-first {% if page == 1 %}disabled{% endif %}">
                                    <a class="page-link" aria-label="Première page">
                                        <span aria-hidden="true"><i class="fa fa-step-backward"></i></span>
                                        <span class="sr-only">Dernière page</span>
                                    </a>
                                </li>
                                <li class="page-item pager-prev {% if page == 1 %}disabled{% endif %}">
                                    <a class="page-link" aria-label="Page précédente">
                                        <span aria-hidden="true"><i class="fa fa-backward"></i></span>
                                        <span class="sr-only">Page précédente</span>
                                    </a>
                                </li>

                                {% for p in range(1, nbPages) %}
                                    <li class="page-item pager-goto {% if p == page %}active{% endif %}" {% if p > 9 %}style="display: none;"{% endif %} value="{{ p }}">
                                        <a class="page-link">{{ p }}</a>
                                    </li>
                                {% endfor %}

                                <li class="page-item pager-next {% if page == nbPages %}disabled{% endif %}">
                                    <a class="page-link" aria-label="Page suivante">
                                        <span aria-hidden="true"><i class="fa fa-forward"></i></span>
                                        <span class="sr-only">Page suivante</span>
                                    </a>
                                </li>
                                <li class="page-item pager-last {% if page == nbPages %}disabled{% endif %}">
                                    <a class="page-link" aria-label="Dernière page">
                                        <span aria-hidden="true"><i class="fa fa-step-forward"></i></span>
                                        <span class="sr-only">Dernière page</span>
                                    </a>
                                </li>
                            </ul>
                        </nav>

                        <div class="mask flex-center" id="pager-loader" style="display: none;">
                            <div class="preloader-wrapper big active">
                                <div class="spinner-layer spinner-blue-only">
                                    <div class="circle-clipper left">
                                    <div class="circle"></div>
                                    </div><div class="gap-patch">
                                    <div class="circle"></div>
                                    </div><div class="circle-clipper right">
                                    <div class="circle"></div>
                                    </div>
                                </div>
                            </div>
                        </div>

                    </div>
                </div>
                <div class="modal fade right" id="blocInfoIndividu" tabindex="-1" role="dialog" aria-labelledby="infoIndividu" aria-hidden="true">
                    <div class="modal-dialog modal-full-height modal-right modal-notify modal-info" role="document">
                        <div class="modal-content" id="contentInfoIndividu"></div>
                    </div>
                </div>
            </div>
            {% if is_granted("ROLE_ADMIN") %}
            <div class="row">
                <div class="col-md-12">
                    <div class="row mb-1">
                        <div class="col-md-2 mt-1">
                            Pour la sélection :
                        </div>
                        <div class="col-md-10">
                                {{ form_start(form_supprime_selection, {'attr' : {'id': 'deleteMultipleForm', 'class': 'form-inline-mdb'}}) }}
                                    <button type="submit" class="btn btn-danger buttonActionCheck disabled" disabled="disabled" href="{{ path("individu_new") }}"><i class="fa fa-trash left"></i> Supprimer</button>
                                {{ form_end(form_supprime_selection) }}
                        </div>
                    </div>
                </div>
            </div>
            {% endif %}
        <!-- /.First column -->
        </div>
    <!-- /.First row -->
    </div>
{% endblock %}
{% block javascripts %}
    <script type="text/javascript">
        function initLinesActions() {
            $('.showBlockInfo').click(function() {
                var url = "{{ path('individu_show', {'id': '0'}) }}";
                url = url.replace("0", $(this).data('id'));
                $.ajax({
                      url: url,
                      dataType: 'html',
                      success: function(data) {
                            $('#contentInfoIndividu').html(data);

                            $('#blocInfoIndividu').modal('show');
                      }
                    });
            });

            $('.lineCheckbox').change(function() {
                if ($('.lineCheckbox:checked').length > 0) {
                    $('.buttonActionCheck').removeClass('disabled').prop('disabled', false);
                }
                else {
                    $('.buttonActionCheck').addClass('disabled').prop('disabled', true);
                }
            });
        }

        $('#deleteMultipleForm').ajaxForm({
            beforeSubmit: function(arr, $form, options) {
                $('.lineCheckbox:checked').each(function() {
                    var dataTable = { name: 'individus[]', value: $(this).data('id') };
                    arr.push(dataTable);
                });
            },
            success: function(responseText, statusText, xhr, $form) {
               window.location.replace('{{ path('individu_index') }}');
            },
            error: function (xhr, status, error) {
                var messages = $.parseJSON(xhr.responseText);
                messages.each(function(key, values) {
                    for (var i = 0; i < values.length; i++) {
                        toastr.error(values[i]);
                    }
                });
            }
        });

        $(function() {
            $('#checkAll').click(function() {
                if ($(this).data('checked')) {
                    $('.lineCheckbox').prop('checked', false);
                    $(this).find('i.fa').attr('class', 'fa fa-square-o');
                    $(this).data('checked', false);
                }
                else {
                    $('.lineCheckbox').prop('checked', true);
                    $(this).find('i.fa').attr('class', 'fa fa-check-square-o');
                    $(this).data('checked', true);
                }
                $('.lineCheckbox').trigger('change');
            });

            $("#listObjets").tablesorter({
                theme: "bootstrap",
                widgets : [ "filter", "print" ],
                sortList: [[0,0]],
                widgetOptions : {
                    filter_external : '#search',
                    filter_columnFilters: false,
                    print_title      : 'Liste des individus',
                    print_now        : true,
                    print_callback   : function(config, $table, printStyle){
                        $table.find(".hidden-print").remove(); // Supprime les colonnes à masquer
                        $.tablesorter.printTable.printOutput( config, $table.html(), printStyle );
                    }
                }
            })
            .tablesorterPager({
                container: $('.pager-container'),
                ajaxUrl: "{{ path("individu_find") }}?page={page}&{sortList:col}",
                customAjaxUrl: function(table, url) {
                    $('#pager-loader').show();
                    if ($('#search').val() != '') {
                        url += "&search="+$('#search').val();
                    }
                    return url;
                },
                ajaxProcessing: function(data){
                    if (data && data.hasOwnProperty('rows')) {
                        var indx, r, row, c, d = data.rows,
                        total = data.total_rows,
                        rows = [],
                        len = d.length;

                        // rows
                        for ( r=0; r < len; r++ ) {
                            row = [];
                            indx = 0;
                            for ( c in d[r] ) {
                                if (typeof(c) === "string") {
                                    if (indx >= 0) {
                                        row[indx++] = d[r][c];
                                    }
                                }
                            }
                            rows.push(row);
                        }

                        $(this.cssGoto).removeClass('active');

                        $(this.cssGoto).hide();

                        var page = this.page+1;
                        var marge = 4;
                        var margeMin = marge;
                        var margeMax = marge;
                        if (page <= marge) {
                            margeMin = marge + (page - marge) - 1;
                            margeMax = marge + (marge - page) + 1;
                        }
                        else if (page > (this.totalPages - marge)) {
                            margeMin = 2 * marge - (this.totalPages - page);
                            margeMax = this.totalPages - page;
                        }
                        $(this.cssGoto).filter(function() {
                            return ($(this).val() >= page-margeMin && $(this).val() <= page+margeMax);
                        }).show();

                        var maxPagesVisible = Math.ceil(total/10);
                        $(this.cssGoto).filter(function() {
                            return ($(this).val() > maxPagesVisible);
                        }).hide();

                        $(this.cssGoto + '[value="'+(this.page+1)+'"]').addClass('active');

                        return [ total, rows ];
                    }
                },

                totalRows: {{ total }},
                filteredRows: {{ total }}

            })
            .bind('pagerComplete', function(event, content){ // pagerChange pageMoved pagerComplete pagerInitialized
                initLinesActions();
                $('#pager-loader').hide();
            });

            $('.clearInput').clearInput();
            $('#printTable').click(function(){
                $('#listObjets').trigger('printTable');
            });

            initLinesActions();
        });
    </script>
{% endblock %}

src/AppBundle/Resources/views/individu/new.html.twig
{% extends '@App/layout.html.twig' %}

{%  block title %}Ajout d'un individu {% endblock %}
{% block breadcrumb %}
    <li class="breadcrumb-item active"><a href="{{ path("individu_index") }}">Gestion des individus</a></li>
    <li class="breadcrumb-item">Ajout d'un individu</li>
{% endblock %}
{% block content %}
    <div class="container-fluid">
        <!-- First row -->
        <div class="row">
            <!-- First column -->
            <div class="col-md-12">
                <div class="row">
                    <div class="col-md-12 mb-1">
                        <div class="card">
                            <div class="card-block">
                                {{ include("@App/individu/form.html.twig") }}
                            </div>
                        </div>
                    </div>
                </div>
            </div>
        </div>

    </div>
{% endblock %}

src/AppBundle/Resources/views/individu/row.html.twig
<tr>
    <td class="hidden-print">
        {{ include('@App/individu/checkbox.html.twig', {'individu' : individu}) }}
    </td>
    <td>{{ individu.identifiant }}</td>
    <td>{{ individu.statut.libelle }}</td>
    <td>{{ individu.nom }}</td>
    <td>{{ individu.prenom }}</td>
    <td>{{ individu.email }}</td>
    <td class="hidden-print">
        <a class="blue-text showBlockInfo" data-id="{{ individu.id }}" data-toggle="tooltip" data-placement="top" title="Voir"><i class="fa fa-eye"></i></a>
        {% if is_granted("ROLE_ADMIN") %}
            <a class="orange-text" data-toggle="tooltip" data-placement="top" title="Modifier" href="{{ path('individu_edit', {'id': individu.id}) }}"><i class="fa fa-pencil"></i></a>
            {{ render(controller('AppBundle:Individu:deleteForm', { 'individu' : individu })) }}
        {% endif %}
    </td>
</tr>

src/AppBundle/Resources/views/individu/show.html.twig
<div class="modal-header">
    <p class="heading lead">{{ individu.prenomNom }}</p>
    <button type="button" class="close" data-dismiss="modal" aria-label="Fermer" title="Fermer">
        <span aria-hidden="true" class="white-text">&times;</span>
    </button>
</div>
<!--Body-->
<div class="modal-body">
    <div class="text-center">
        <i class="fa fa-info-circle fa-4x mb-1 animated rotateIn"></i>
    </div>
    <ul class="striped">
        <li><strong>Identifiant ({{ individu.statut.typeIdentifiant }}) :</strong> {{ individu.identifiant }}</li>
        <li><strong>Statut :</strong> {{ individu.statut.libelle }}</li>
        <li><strong>Email :</strong> {{ individu.email }}</li>
        <li><strong>Téléphone :</strong> {{ individu.telephone }}</li>
        <li><strong>Date de naissance :</strong> {{ individu.dateNaissance|localizeddate('none', 'none', app.request.locale, "Europe/Paris", "d MMMM Y") }}</li>
        <li><div class="font-weight-bold text-center"><i class="fa fa-group"></i> Groupes :</div></li>
    </ul>
    {% if individu.groupes.count > 0 %}
        <div style="max-height: 200px; position:relative; overflow: auto;">
            {% for groupe in individu.allGroupes %}
                <div>{{ groupe.nom }}</div>
            {% endfor %}
        </div>
    {% endif %}
</div>
<!--Footer-->
<div class="modal-footer">
    {% if is_granted("ROLE_ADMIN") %}
        <a type="button" class="btn btn-orange" href="{{ path('individu_edit', {'id': individu.id}) }}"><i class="fa fa-pencil left"></i> Modifier</a>
        {{ form_start(delete_form, {'attr': {'class': 'd-inline', 'onSubmit': 'return confirm("' ~ confirm_message ~ '")'}}) }}
        <button type="submit" class="btn btn-danger align-content-center"><i class="fa fa-trash left"></i> Supprimer</button>
        {{ form_rest(delete_form) }}
        {{ form_end(delete_form) }}
    {% endif %}
</div>